# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kalyaka/pocketbook_free/antiword

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kalyaka/pocketbook_free/antiword

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kalyaka/pocketbook_free/antiword/CMakeFiles /home/kalyaka/pocketbook_free/antiword/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kalyaka/pocketbook_free/antiword/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named antiword

# Build rule for target.
antiword: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antiword
.PHONY : antiword

# fast build rule for target.
antiword/fast:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/build
.PHONY : antiword/fast

src/asc85enc.o: src/asc85enc.c.o
.PHONY : src/asc85enc.o

# target to build an object file
src/asc85enc.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/asc85enc.c.o
.PHONY : src/asc85enc.c.o

src/asc85enc.i: src/asc85enc.c.i
.PHONY : src/asc85enc.i

# target to preprocess a source file
src/asc85enc.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/asc85enc.c.i
.PHONY : src/asc85enc.c.i

src/asc85enc.s: src/asc85enc.c.s
.PHONY : src/asc85enc.s

# target to generate assembly for a file
src/asc85enc.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/asc85enc.c.s
.PHONY : src/asc85enc.c.s

src/blocklist.o: src/blocklist.c.o
.PHONY : src/blocklist.o

# target to build an object file
src/blocklist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/blocklist.c.o
.PHONY : src/blocklist.c.o

src/blocklist.i: src/blocklist.c.i
.PHONY : src/blocklist.i

# target to preprocess a source file
src/blocklist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/blocklist.c.i
.PHONY : src/blocklist.c.i

src/blocklist.s: src/blocklist.c.s
.PHONY : src/blocklist.s

# target to generate assembly for a file
src/blocklist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/blocklist.c.s
.PHONY : src/blocklist.c.s

src/chartrans.o: src/chartrans.c.o
.PHONY : src/chartrans.o

# target to build an object file
src/chartrans.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/chartrans.c.o
.PHONY : src/chartrans.c.o

src/chartrans.i: src/chartrans.c.i
.PHONY : src/chartrans.i

# target to preprocess a source file
src/chartrans.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/chartrans.c.i
.PHONY : src/chartrans.c.i

src/chartrans.s: src/chartrans.c.s
.PHONY : src/chartrans.s

# target to generate assembly for a file
src/chartrans.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/chartrans.c.s
.PHONY : src/chartrans.c.s

src/datalist.o: src/datalist.c.o
.PHONY : src/datalist.o

# target to build an object file
src/datalist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/datalist.c.o
.PHONY : src/datalist.c.o

src/datalist.i: src/datalist.c.i
.PHONY : src/datalist.i

# target to preprocess a source file
src/datalist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/datalist.c.i
.PHONY : src/datalist.c.i

src/datalist.s: src/datalist.c.s
.PHONY : src/datalist.s

# target to generate assembly for a file
src/datalist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/datalist.c.s
.PHONY : src/datalist.c.s

src/depot.o: src/depot.c.o
.PHONY : src/depot.o

# target to build an object file
src/depot.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/depot.c.o
.PHONY : src/depot.c.o

src/depot.i: src/depot.c.i
.PHONY : src/depot.i

# target to preprocess a source file
src/depot.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/depot.c.i
.PHONY : src/depot.c.i

src/depot.s: src/depot.c.s
.PHONY : src/depot.s

# target to generate assembly for a file
src/depot.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/depot.c.s
.PHONY : src/depot.c.s

src/dib2eps.o: src/dib2eps.c.o
.PHONY : src/dib2eps.o

# target to build an object file
src/dib2eps.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/dib2eps.c.o
.PHONY : src/dib2eps.c.o

src/dib2eps.i: src/dib2eps.c.i
.PHONY : src/dib2eps.i

# target to preprocess a source file
src/dib2eps.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/dib2eps.c.i
.PHONY : src/dib2eps.c.i

src/dib2eps.s: src/dib2eps.c.s
.PHONY : src/dib2eps.s

# target to generate assembly for a file
src/dib2eps.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/dib2eps.c.s
.PHONY : src/dib2eps.c.s

src/doclist.o: src/doclist.c.o
.PHONY : src/doclist.o

# target to build an object file
src/doclist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/doclist.c.o
.PHONY : src/doclist.c.o

src/doclist.i: src/doclist.c.i
.PHONY : src/doclist.i

# target to preprocess a source file
src/doclist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/doclist.c.i
.PHONY : src/doclist.c.i

src/doclist.s: src/doclist.c.s
.PHONY : src/doclist.s

# target to generate assembly for a file
src/doclist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/doclist.c.s
.PHONY : src/doclist.c.s

src/fail.o: src/fail.c.o
.PHONY : src/fail.o

# target to build an object file
src/fail.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fail.c.o
.PHONY : src/fail.c.o

src/fail.i: src/fail.c.i
.PHONY : src/fail.i

# target to preprocess a source file
src/fail.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fail.c.i
.PHONY : src/fail.c.i

src/fail.s: src/fail.c.s
.PHONY : src/fail.s

# target to generate assembly for a file
src/fail.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fail.c.s
.PHONY : src/fail.c.s

src/finddata.o: src/finddata.c.o
.PHONY : src/finddata.o

# target to build an object file
src/finddata.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/finddata.c.o
.PHONY : src/finddata.c.o

src/finddata.i: src/finddata.c.i
.PHONY : src/finddata.i

# target to preprocess a source file
src/finddata.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/finddata.c.i
.PHONY : src/finddata.c.i

src/finddata.s: src/finddata.c.s
.PHONY : src/finddata.s

# target to generate assembly for a file
src/finddata.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/finddata.c.s
.PHONY : src/finddata.c.s

src/findtext.o: src/findtext.c.o
.PHONY : src/findtext.o

# target to build an object file
src/findtext.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/findtext.c.o
.PHONY : src/findtext.c.o

src/findtext.i: src/findtext.c.i
.PHONY : src/findtext.i

# target to preprocess a source file
src/findtext.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/findtext.c.i
.PHONY : src/findtext.c.i

src/findtext.s: src/findtext.c.s
.PHONY : src/findtext.s

# target to generate assembly for a file
src/findtext.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/findtext.c.s
.PHONY : src/findtext.c.s

src/fmt_text.o: src/fmt_text.c.o
.PHONY : src/fmt_text.o

# target to build an object file
src/fmt_text.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fmt_text.c.o
.PHONY : src/fmt_text.c.o

src/fmt_text.i: src/fmt_text.c.i
.PHONY : src/fmt_text.i

# target to preprocess a source file
src/fmt_text.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fmt_text.c.i
.PHONY : src/fmt_text.c.i

src/fmt_text.s: src/fmt_text.c.s
.PHONY : src/fmt_text.s

# target to generate assembly for a file
src/fmt_text.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fmt_text.c.s
.PHONY : src/fmt_text.c.s

src/fontlist.o: src/fontlist.c.o
.PHONY : src/fontlist.o

# target to build an object file
src/fontlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fontlist.c.o
.PHONY : src/fontlist.c.o

src/fontlist.i: src/fontlist.c.i
.PHONY : src/fontlist.i

# target to preprocess a source file
src/fontlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fontlist.c.i
.PHONY : src/fontlist.c.i

src/fontlist.s: src/fontlist.c.s
.PHONY : src/fontlist.s

# target to generate assembly for a file
src/fontlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fontlist.c.s
.PHONY : src/fontlist.c.s

src/fonts.o: src/fonts.c.o
.PHONY : src/fonts.o

# target to build an object file
src/fonts.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts.c.o
.PHONY : src/fonts.c.o

src/fonts.i: src/fonts.c.i
.PHONY : src/fonts.i

# target to preprocess a source file
src/fonts.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts.c.i
.PHONY : src/fonts.c.i

src/fonts.s: src/fonts.c.s
.PHONY : src/fonts.s

# target to generate assembly for a file
src/fonts.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts.c.s
.PHONY : src/fonts.c.s

src/fonts_u.o: src/fonts_u.c.o
.PHONY : src/fonts_u.o

# target to build an object file
src/fonts_u.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts_u.c.o
.PHONY : src/fonts_u.c.o

src/fonts_u.i: src/fonts_u.c.i
.PHONY : src/fonts_u.i

# target to preprocess a source file
src/fonts_u.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts_u.c.i
.PHONY : src/fonts_u.c.i

src/fonts_u.s: src/fonts_u.c.s
.PHONY : src/fonts_u.s

# target to generate assembly for a file
src/fonts_u.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/fonts_u.c.s
.PHONY : src/fonts_u.c.s

src/hdrftrlist.o: src/hdrftrlist.c.o
.PHONY : src/hdrftrlist.o

# target to build an object file
src/hdrftrlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/hdrftrlist.c.o
.PHONY : src/hdrftrlist.c.o

src/hdrftrlist.i: src/hdrftrlist.c.i
.PHONY : src/hdrftrlist.i

# target to preprocess a source file
src/hdrftrlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/hdrftrlist.c.i
.PHONY : src/hdrftrlist.c.i

src/hdrftrlist.s: src/hdrftrlist.c.s
.PHONY : src/hdrftrlist.s

# target to generate assembly for a file
src/hdrftrlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/hdrftrlist.c.s
.PHONY : src/hdrftrlist.c.s

src/imgexam.o: src/imgexam.c.o
.PHONY : src/imgexam.o

# target to build an object file
src/imgexam.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgexam.c.o
.PHONY : src/imgexam.c.o

src/imgexam.i: src/imgexam.c.i
.PHONY : src/imgexam.i

# target to preprocess a source file
src/imgexam.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgexam.c.i
.PHONY : src/imgexam.c.i

src/imgexam.s: src/imgexam.c.s
.PHONY : src/imgexam.s

# target to generate assembly for a file
src/imgexam.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgexam.c.s
.PHONY : src/imgexam.c.s

src/imgtrans.o: src/imgtrans.c.o
.PHONY : src/imgtrans.o

# target to build an object file
src/imgtrans.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgtrans.c.o
.PHONY : src/imgtrans.c.o

src/imgtrans.i: src/imgtrans.c.i
.PHONY : src/imgtrans.i

# target to preprocess a source file
src/imgtrans.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgtrans.c.i
.PHONY : src/imgtrans.c.i

src/imgtrans.s: src/imgtrans.c.s
.PHONY : src/imgtrans.s

# target to generate assembly for a file
src/imgtrans.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/imgtrans.c.s
.PHONY : src/imgtrans.c.s

src/jpeg2eps.o: src/jpeg2eps.c.o
.PHONY : src/jpeg2eps.o

# target to build an object file
src/jpeg2eps.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/jpeg2eps.c.o
.PHONY : src/jpeg2eps.c.o

src/jpeg2eps.i: src/jpeg2eps.c.i
.PHONY : src/jpeg2eps.i

# target to preprocess a source file
src/jpeg2eps.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/jpeg2eps.c.i
.PHONY : src/jpeg2eps.c.i

src/jpeg2eps.s: src/jpeg2eps.c.s
.PHONY : src/jpeg2eps.s

# target to generate assembly for a file
src/jpeg2eps.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/jpeg2eps.c.s
.PHONY : src/jpeg2eps.c.s

src/listlist.o: src/listlist.c.o
.PHONY : src/listlist.o

# target to build an object file
src/listlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/listlist.c.o
.PHONY : src/listlist.c.o

src/listlist.i: src/listlist.c.i
.PHONY : src/listlist.i

# target to preprocess a source file
src/listlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/listlist.c.i
.PHONY : src/listlist.c.i

src/listlist.s: src/listlist.c.s
.PHONY : src/listlist.s

# target to generate assembly for a file
src/listlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/listlist.c.s
.PHONY : src/listlist.c.s

src/main_u.o: src/main_u.c.o
.PHONY : src/main_u.o

# target to build an object file
src/main_u.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/main_u.c.o
.PHONY : src/main_u.c.o

src/main_u.i: src/main_u.c.i
.PHONY : src/main_u.i

# target to preprocess a source file
src/main_u.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/main_u.c.i
.PHONY : src/main_u.c.i

src/main_u.s: src/main_u.c.s
.PHONY : src/main_u.s

# target to generate assembly for a file
src/main_u.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/main_u.c.s
.PHONY : src/main_u.c.s

src/misc.o: src/misc.c.o
.PHONY : src/misc.o

# target to build an object file
src/misc.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/misc.c.o
.PHONY : src/misc.c.o

src/misc.i: src/misc.c.i
.PHONY : src/misc.i

# target to preprocess a source file
src/misc.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/misc.c.i
.PHONY : src/misc.c.i

src/misc.s: src/misc.c.s
.PHONY : src/misc.s

# target to generate assembly for a file
src/misc.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/misc.c.s
.PHONY : src/misc.c.s

src/notes.o: src/notes.c.o
.PHONY : src/notes.o

# target to build an object file
src/notes.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/notes.c.o
.PHONY : src/notes.c.o

src/notes.i: src/notes.c.i
.PHONY : src/notes.i

# target to preprocess a source file
src/notes.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/notes.c.i
.PHONY : src/notes.c.i

src/notes.s: src/notes.c.s
.PHONY : src/notes.s

# target to generate assembly for a file
src/notes.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/notes.c.s
.PHONY : src/notes.c.s

src/options.o: src/options.c.o
.PHONY : src/options.o

# target to build an object file
src/options.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/options.c.o
.PHONY : src/options.c.o

src/options.i: src/options.c.i
.PHONY : src/options.i

# target to preprocess a source file
src/options.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/options.c.i
.PHONY : src/options.c.i

src/options.s: src/options.c.s
.PHONY : src/options.s

# target to generate assembly for a file
src/options.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/options.c.s
.PHONY : src/options.c.s

src/out2window.o: src/out2window.c.o
.PHONY : src/out2window.o

# target to build an object file
src/out2window.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/out2window.c.o
.PHONY : src/out2window.c.o

src/out2window.i: src/out2window.c.i
.PHONY : src/out2window.i

# target to preprocess a source file
src/out2window.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/out2window.c.i
.PHONY : src/out2window.c.i

src/out2window.s: src/out2window.c.s
.PHONY : src/out2window.s

# target to generate assembly for a file
src/out2window.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/out2window.c.s
.PHONY : src/out2window.c.s

src/output.o: src/output.c.o
.PHONY : src/output.o

# target to build an object file
src/output.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/output.c.o
.PHONY : src/output.c.o

src/output.i: src/output.c.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/output.c.i
.PHONY : src/output.c.i

src/output.s: src/output.c.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/output.c.s
.PHONY : src/output.c.s

src/pdf.o: src/pdf.c.o
.PHONY : src/pdf.o

# target to build an object file
src/pdf.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pdf.c.o
.PHONY : src/pdf.c.o

src/pdf.i: src/pdf.c.i
.PHONY : src/pdf.i

# target to preprocess a source file
src/pdf.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pdf.c.i
.PHONY : src/pdf.c.i

src/pdf.s: src/pdf.c.s
.PHONY : src/pdf.s

# target to generate assembly for a file
src/pdf.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pdf.c.s
.PHONY : src/pdf.c.s

src/pictlist.o: src/pictlist.c.o
.PHONY : src/pictlist.o

# target to build an object file
src/pictlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pictlist.c.o
.PHONY : src/pictlist.c.o

src/pictlist.i: src/pictlist.c.i
.PHONY : src/pictlist.i

# target to preprocess a source file
src/pictlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pictlist.c.i
.PHONY : src/pictlist.c.i

src/pictlist.s: src/pictlist.c.s
.PHONY : src/pictlist.s

# target to generate assembly for a file
src/pictlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/pictlist.c.s
.PHONY : src/pictlist.c.s

src/png2eps.o: src/png2eps.c.o
.PHONY : src/png2eps.o

# target to build an object file
src/png2eps.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/png2eps.c.o
.PHONY : src/png2eps.c.o

src/png2eps.i: src/png2eps.c.i
.PHONY : src/png2eps.i

# target to preprocess a source file
src/png2eps.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/png2eps.c.i
.PHONY : src/png2eps.c.i

src/png2eps.s: src/png2eps.c.s
.PHONY : src/png2eps.s

# target to generate assembly for a file
src/png2eps.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/png2eps.c.s
.PHONY : src/png2eps.c.s

src/postscript.o: src/postscript.c.o
.PHONY : src/postscript.o

# target to build an object file
src/postscript.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/postscript.c.o
.PHONY : src/postscript.c.o

src/postscript.i: src/postscript.c.i
.PHONY : src/postscript.i

# target to preprocess a source file
src/postscript.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/postscript.c.i
.PHONY : src/postscript.c.i

src/postscript.s: src/postscript.c.s
.PHONY : src/postscript.s

# target to generate assembly for a file
src/postscript.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/postscript.c.s
.PHONY : src/postscript.c.s

src/prop0.o: src/prop0.c.o
.PHONY : src/prop0.o

# target to build an object file
src/prop0.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop0.c.o
.PHONY : src/prop0.c.o

src/prop0.i: src/prop0.c.i
.PHONY : src/prop0.i

# target to preprocess a source file
src/prop0.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop0.c.i
.PHONY : src/prop0.c.i

src/prop0.s: src/prop0.c.s
.PHONY : src/prop0.s

# target to generate assembly for a file
src/prop0.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop0.c.s
.PHONY : src/prop0.c.s

src/prop2.o: src/prop2.c.o
.PHONY : src/prop2.o

# target to build an object file
src/prop2.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop2.c.o
.PHONY : src/prop2.c.o

src/prop2.i: src/prop2.c.i
.PHONY : src/prop2.i

# target to preprocess a source file
src/prop2.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop2.c.i
.PHONY : src/prop2.c.i

src/prop2.s: src/prop2.c.s
.PHONY : src/prop2.s

# target to generate assembly for a file
src/prop2.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop2.c.s
.PHONY : src/prop2.c.s

src/prop6.o: src/prop6.c.o
.PHONY : src/prop6.o

# target to build an object file
src/prop6.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop6.c.o
.PHONY : src/prop6.c.o

src/prop6.i: src/prop6.c.i
.PHONY : src/prop6.i

# target to preprocess a source file
src/prop6.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop6.c.i
.PHONY : src/prop6.c.i

src/prop6.s: src/prop6.c.s
.PHONY : src/prop6.s

# target to generate assembly for a file
src/prop6.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop6.c.s
.PHONY : src/prop6.c.s

src/prop8.o: src/prop8.c.o
.PHONY : src/prop8.o

# target to build an object file
src/prop8.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop8.c.o
.PHONY : src/prop8.c.o

src/prop8.i: src/prop8.c.i
.PHONY : src/prop8.i

# target to preprocess a source file
src/prop8.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop8.c.i
.PHONY : src/prop8.c.i

src/prop8.s: src/prop8.c.s
.PHONY : src/prop8.s

# target to generate assembly for a file
src/prop8.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/prop8.c.s
.PHONY : src/prop8.c.s

src/properties.o: src/properties.c.o
.PHONY : src/properties.o

# target to build an object file
src/properties.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/properties.c.o
.PHONY : src/properties.c.o

src/properties.i: src/properties.c.i
.PHONY : src/properties.i

# target to preprocess a source file
src/properties.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/properties.c.i
.PHONY : src/properties.c.i

src/properties.s: src/properties.c.s
.PHONY : src/properties.s

# target to generate assembly for a file
src/properties.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/properties.c.s
.PHONY : src/properties.c.s

src/propmod.o: src/propmod.c.o
.PHONY : src/propmod.o

# target to build an object file
src/propmod.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/propmod.c.o
.PHONY : src/propmod.c.o

src/propmod.i: src/propmod.c.i
.PHONY : src/propmod.i

# target to preprocess a source file
src/propmod.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/propmod.c.i
.PHONY : src/propmod.c.i

src/propmod.s: src/propmod.c.s
.PHONY : src/propmod.s

# target to generate assembly for a file
src/propmod.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/propmod.c.s
.PHONY : src/propmod.c.s

src/rowlist.o: src/rowlist.c.o
.PHONY : src/rowlist.o

# target to build an object file
src/rowlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/rowlist.c.o
.PHONY : src/rowlist.c.o

src/rowlist.i: src/rowlist.c.i
.PHONY : src/rowlist.i

# target to preprocess a source file
src/rowlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/rowlist.c.i
.PHONY : src/rowlist.c.i

src/rowlist.s: src/rowlist.c.s
.PHONY : src/rowlist.s

# target to generate assembly for a file
src/rowlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/rowlist.c.s
.PHONY : src/rowlist.c.s

src/sectlist.o: src/sectlist.c.o
.PHONY : src/sectlist.o

# target to build an object file
src/sectlist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/sectlist.c.o
.PHONY : src/sectlist.c.o

src/sectlist.i: src/sectlist.c.i
.PHONY : src/sectlist.i

# target to preprocess a source file
src/sectlist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/sectlist.c.i
.PHONY : src/sectlist.c.i

src/sectlist.s: src/sectlist.c.s
.PHONY : src/sectlist.s

# target to generate assembly for a file
src/sectlist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/sectlist.c.s
.PHONY : src/sectlist.c.s

src/stylelist.o: src/stylelist.c.o
.PHONY : src/stylelist.o

# target to build an object file
src/stylelist.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylelist.c.o
.PHONY : src/stylelist.c.o

src/stylelist.i: src/stylelist.c.i
.PHONY : src/stylelist.i

# target to preprocess a source file
src/stylelist.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylelist.c.i
.PHONY : src/stylelist.c.i

src/stylelist.s: src/stylelist.c.s
.PHONY : src/stylelist.s

# target to generate assembly for a file
src/stylelist.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylelist.c.s
.PHONY : src/stylelist.c.s

src/stylesheet.o: src/stylesheet.c.o
.PHONY : src/stylesheet.o

# target to build an object file
src/stylesheet.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylesheet.c.o
.PHONY : src/stylesheet.c.o

src/stylesheet.i: src/stylesheet.c.i
.PHONY : src/stylesheet.i

# target to preprocess a source file
src/stylesheet.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylesheet.c.i
.PHONY : src/stylesheet.c.i

src/stylesheet.s: src/stylesheet.c.s
.PHONY : src/stylesheet.s

# target to generate assembly for a file
src/stylesheet.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/stylesheet.c.s
.PHONY : src/stylesheet.c.s

src/summary.o: src/summary.c.o
.PHONY : src/summary.o

# target to build an object file
src/summary.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/summary.c.o
.PHONY : src/summary.c.o

src/summary.i: src/summary.c.i
.PHONY : src/summary.i

# target to preprocess a source file
src/summary.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/summary.c.i
.PHONY : src/summary.c.i

src/summary.s: src/summary.c.s
.PHONY : src/summary.s

# target to generate assembly for a file
src/summary.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/summary.c.s
.PHONY : src/summary.c.s

src/tabstop.o: src/tabstop.c.o
.PHONY : src/tabstop.o

# target to build an object file
src/tabstop.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/tabstop.c.o
.PHONY : src/tabstop.c.o

src/tabstop.i: src/tabstop.c.i
.PHONY : src/tabstop.i

# target to preprocess a source file
src/tabstop.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/tabstop.c.i
.PHONY : src/tabstop.c.i

src/tabstop.s: src/tabstop.c.s
.PHONY : src/tabstop.s

# target to generate assembly for a file
src/tabstop.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/tabstop.c.s
.PHONY : src/tabstop.c.s

src/text.o: src/text.c.o
.PHONY : src/text.o

# target to build an object file
src/text.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/text.c.o
.PHONY : src/text.c.o

src/text.i: src/text.c.i
.PHONY : src/text.i

# target to preprocess a source file
src/text.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/text.c.i
.PHONY : src/text.c.i

src/text.s: src/text.c.s
.PHONY : src/text.s

# target to generate assembly for a file
src/text.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/text.c.s
.PHONY : src/text.c.s

src/unix.o: src/unix.c.o
.PHONY : src/unix.o

# target to build an object file
src/unix.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/unix.c.o
.PHONY : src/unix.c.o

src/unix.i: src/unix.c.i
.PHONY : src/unix.i

# target to preprocess a source file
src/unix.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/unix.c.i
.PHONY : src/unix.c.i

src/unix.s: src/unix.c.s
.PHONY : src/unix.s

# target to generate assembly for a file
src/unix.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/unix.c.s
.PHONY : src/unix.c.s

src/utf8.o: src/utf8.c.o
.PHONY : src/utf8.o

# target to build an object file
src/utf8.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/utf8.c.o
.PHONY : src/utf8.c.o

src/utf8.i: src/utf8.c.i
.PHONY : src/utf8.i

# target to preprocess a source file
src/utf8.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/utf8.c.i
.PHONY : src/utf8.c.i

src/utf8.s: src/utf8.c.s
.PHONY : src/utf8.s

# target to generate assembly for a file
src/utf8.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/utf8.c.s
.PHONY : src/utf8.c.s

src/word2text.o: src/word2text.c.o
.PHONY : src/word2text.o

# target to build an object file
src/word2text.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/word2text.c.o
.PHONY : src/word2text.c.o

src/word2text.i: src/word2text.c.i
.PHONY : src/word2text.i

# target to preprocess a source file
src/word2text.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/word2text.c.i
.PHONY : src/word2text.c.i

src/word2text.s: src/word2text.c.s
.PHONY : src/word2text.s

# target to generate assembly for a file
src/word2text.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/word2text.c.s
.PHONY : src/word2text.c.s

src/worddos.o: src/worddos.c.o
.PHONY : src/worddos.o

# target to build an object file
src/worddos.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/worddos.c.o
.PHONY : src/worddos.c.o

src/worddos.i: src/worddos.c.i
.PHONY : src/worddos.i

# target to preprocess a source file
src/worddos.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/worddos.c.i
.PHONY : src/worddos.c.i

src/worddos.s: src/worddos.c.s
.PHONY : src/worddos.s

# target to generate assembly for a file
src/worddos.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/worddos.c.s
.PHONY : src/worddos.c.s

src/wordlib.o: src/wordlib.c.o
.PHONY : src/wordlib.o

# target to build an object file
src/wordlib.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordlib.c.o
.PHONY : src/wordlib.c.o

src/wordlib.i: src/wordlib.c.i
.PHONY : src/wordlib.i

# target to preprocess a source file
src/wordlib.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordlib.c.i
.PHONY : src/wordlib.c.i

src/wordlib.s: src/wordlib.c.s
.PHONY : src/wordlib.s

# target to generate assembly for a file
src/wordlib.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordlib.c.s
.PHONY : src/wordlib.c.s

src/wordmac.o: src/wordmac.c.o
.PHONY : src/wordmac.o

# target to build an object file
src/wordmac.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordmac.c.o
.PHONY : src/wordmac.c.o

src/wordmac.i: src/wordmac.c.i
.PHONY : src/wordmac.i

# target to preprocess a source file
src/wordmac.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordmac.c.i
.PHONY : src/wordmac.c.i

src/wordmac.s: src/wordmac.c.s
.PHONY : src/wordmac.s

# target to generate assembly for a file
src/wordmac.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordmac.c.s
.PHONY : src/wordmac.c.s

src/wordole.o: src/wordole.c.o
.PHONY : src/wordole.o

# target to build an object file
src/wordole.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordole.c.o
.PHONY : src/wordole.c.o

src/wordole.i: src/wordole.c.i
.PHONY : src/wordole.i

# target to preprocess a source file
src/wordole.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordole.c.i
.PHONY : src/wordole.c.i

src/wordole.s: src/wordole.c.s
.PHONY : src/wordole.s

# target to generate assembly for a file
src/wordole.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordole.c.s
.PHONY : src/wordole.c.s

src/wordwin.o: src/wordwin.c.o
.PHONY : src/wordwin.o

# target to build an object file
src/wordwin.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordwin.c.o
.PHONY : src/wordwin.c.o

src/wordwin.i: src/wordwin.c.i
.PHONY : src/wordwin.i

# target to preprocess a source file
src/wordwin.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordwin.c.i
.PHONY : src/wordwin.c.i

src/wordwin.s: src/wordwin.c.s
.PHONY : src/wordwin.s

# target to generate assembly for a file
src/wordwin.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/wordwin.c.s
.PHONY : src/wordwin.c.s

src/xmalloc.o: src/xmalloc.c.o
.PHONY : src/xmalloc.o

# target to build an object file
src/xmalloc.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xmalloc.c.o
.PHONY : src/xmalloc.c.o

src/xmalloc.i: src/xmalloc.c.i
.PHONY : src/xmalloc.i

# target to preprocess a source file
src/xmalloc.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xmalloc.c.i
.PHONY : src/xmalloc.c.i

src/xmalloc.s: src/xmalloc.c.s
.PHONY : src/xmalloc.s

# target to generate assembly for a file
src/xmalloc.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xmalloc.c.s
.PHONY : src/xmalloc.c.s

src/xml.o: src/xml.c.o
.PHONY : src/xml.o

# target to build an object file
src/xml.c.o:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xml.c.o
.PHONY : src/xml.c.o

src/xml.i: src/xml.c.i
.PHONY : src/xml.i

# target to preprocess a source file
src/xml.c.i:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xml.c.i
.PHONY : src/xml.c.i

src/xml.s: src/xml.c.s
.PHONY : src/xml.s

# target to generate assembly for a file
src/xml.c.s:
	$(MAKE) -f CMakeFiles/antiword.dir/build.make CMakeFiles/antiword.dir/src/xml.c.s
.PHONY : src/xml.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... antiword"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/asc85enc.o"
	@echo "... src/asc85enc.i"
	@echo "... src/asc85enc.s"
	@echo "... src/blocklist.o"
	@echo "... src/blocklist.i"
	@echo "... src/blocklist.s"
	@echo "... src/chartrans.o"
	@echo "... src/chartrans.i"
	@echo "... src/chartrans.s"
	@echo "... src/datalist.o"
	@echo "... src/datalist.i"
	@echo "... src/datalist.s"
	@echo "... src/depot.o"
	@echo "... src/depot.i"
	@echo "... src/depot.s"
	@echo "... src/dib2eps.o"
	@echo "... src/dib2eps.i"
	@echo "... src/dib2eps.s"
	@echo "... src/doclist.o"
	@echo "... src/doclist.i"
	@echo "... src/doclist.s"
	@echo "... src/fail.o"
	@echo "... src/fail.i"
	@echo "... src/fail.s"
	@echo "... src/finddata.o"
	@echo "... src/finddata.i"
	@echo "... src/finddata.s"
	@echo "... src/findtext.o"
	@echo "... src/findtext.i"
	@echo "... src/findtext.s"
	@echo "... src/fmt_text.o"
	@echo "... src/fmt_text.i"
	@echo "... src/fmt_text.s"
	@echo "... src/fontlist.o"
	@echo "... src/fontlist.i"
	@echo "... src/fontlist.s"
	@echo "... src/fonts.o"
	@echo "... src/fonts.i"
	@echo "... src/fonts.s"
	@echo "... src/fonts_u.o"
	@echo "... src/fonts_u.i"
	@echo "... src/fonts_u.s"
	@echo "... src/hdrftrlist.o"
	@echo "... src/hdrftrlist.i"
	@echo "... src/hdrftrlist.s"
	@echo "... src/imgexam.o"
	@echo "... src/imgexam.i"
	@echo "... src/imgexam.s"
	@echo "... src/imgtrans.o"
	@echo "... src/imgtrans.i"
	@echo "... src/imgtrans.s"
	@echo "... src/jpeg2eps.o"
	@echo "... src/jpeg2eps.i"
	@echo "... src/jpeg2eps.s"
	@echo "... src/listlist.o"
	@echo "... src/listlist.i"
	@echo "... src/listlist.s"
	@echo "... src/main_u.o"
	@echo "... src/main_u.i"
	@echo "... src/main_u.s"
	@echo "... src/misc.o"
	@echo "... src/misc.i"
	@echo "... src/misc.s"
	@echo "... src/notes.o"
	@echo "... src/notes.i"
	@echo "... src/notes.s"
	@echo "... src/options.o"
	@echo "... src/options.i"
	@echo "... src/options.s"
	@echo "... src/out2window.o"
	@echo "... src/out2window.i"
	@echo "... src/out2window.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/pdf.o"
	@echo "... src/pdf.i"
	@echo "... src/pdf.s"
	@echo "... src/pictlist.o"
	@echo "... src/pictlist.i"
	@echo "... src/pictlist.s"
	@echo "... src/png2eps.o"
	@echo "... src/png2eps.i"
	@echo "... src/png2eps.s"
	@echo "... src/postscript.o"
	@echo "... src/postscript.i"
	@echo "... src/postscript.s"
	@echo "... src/prop0.o"
	@echo "... src/prop0.i"
	@echo "... src/prop0.s"
	@echo "... src/prop2.o"
	@echo "... src/prop2.i"
	@echo "... src/prop2.s"
	@echo "... src/prop6.o"
	@echo "... src/prop6.i"
	@echo "... src/prop6.s"
	@echo "... src/prop8.o"
	@echo "... src/prop8.i"
	@echo "... src/prop8.s"
	@echo "... src/properties.o"
	@echo "... src/properties.i"
	@echo "... src/properties.s"
	@echo "... src/propmod.o"
	@echo "... src/propmod.i"
	@echo "... src/propmod.s"
	@echo "... src/rowlist.o"
	@echo "... src/rowlist.i"
	@echo "... src/rowlist.s"
	@echo "... src/sectlist.o"
	@echo "... src/sectlist.i"
	@echo "... src/sectlist.s"
	@echo "... src/stylelist.o"
	@echo "... src/stylelist.i"
	@echo "... src/stylelist.s"
	@echo "... src/stylesheet.o"
	@echo "... src/stylesheet.i"
	@echo "... src/stylesheet.s"
	@echo "... src/summary.o"
	@echo "... src/summary.i"
	@echo "... src/summary.s"
	@echo "... src/tabstop.o"
	@echo "... src/tabstop.i"
	@echo "... src/tabstop.s"
	@echo "... src/text.o"
	@echo "... src/text.i"
	@echo "... src/text.s"
	@echo "... src/unix.o"
	@echo "... src/unix.i"
	@echo "... src/unix.s"
	@echo "... src/utf8.o"
	@echo "... src/utf8.i"
	@echo "... src/utf8.s"
	@echo "... src/word2text.o"
	@echo "... src/word2text.i"
	@echo "... src/word2text.s"
	@echo "... src/worddos.o"
	@echo "... src/worddos.i"
	@echo "... src/worddos.s"
	@echo "... src/wordlib.o"
	@echo "... src/wordlib.i"
	@echo "... src/wordlib.s"
	@echo "... src/wordmac.o"
	@echo "... src/wordmac.i"
	@echo "... src/wordmac.s"
	@echo "... src/wordole.o"
	@echo "... src/wordole.i"
	@echo "... src/wordole.s"
	@echo "... src/wordwin.o"
	@echo "... src/wordwin.i"
	@echo "... src/wordwin.s"
	@echo "... src/xmalloc.o"
	@echo "... src/xmalloc.i"
	@echo "... src/xmalloc.s"
	@echo "... src/xml.o"
	@echo "... src/xml.i"
	@echo "... src/xml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

